name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  changed-files:
    name: Changed files
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.files-changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check changed files
        id: files-changed
        uses: tj-actions/changed-files@v41
        with:
          files: |
            src/**
            package*.json
            tsconfig.json
            jest.config.js
            webpack.config.js
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ jobs.changed-files.outputs.files_changed == true } }}
    needs: changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: dist
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ jobs.changed-files.outputs.files_changed == true } }}
    needs: changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: ${{ jobs.changed-files.outputs.files_changed == true } }}
    needs: changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
